# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b924241c4c2dc00e41ae7c967e6c99fec12ede61b5fe16551762fea01d8be563d18bae34fbef8159d6ecdf3b40fd41d49640b5448b4398efd36ab7625faa8e

test:
  secret_key_base: caba94a1315b9a58d227c414f7fe2f8ceaf079f6b1541aca77343730a0a8cdc9d86613bb8e261d7d6dfb90da84f5cb08d59aa60f1296c6c0f459c9222a59652b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
